version: '2'

services :
 mongo:
   image: 'library/mongo:3.2.8'
   ports:
     - '27017:27017'
   #networks:
   #   vpcbr:
   #     ipv4_address: 10.5.0.7
   volumes:
     - './db/mongodb:/data/db'

 mysql:
   image: 'mysql:5.5.54'
   ports:
     - '3306:3306'
   #networks:
   #   vpcbr:
   #     ipv4_address: 10.5.0.6
   environment:
     MYSQL_ROOT_PASSWORD: 123456
     MYSQL_USER: demo
     MYSQL_PASSWORD: 123456
     MYSQL_DATABASE: some_database
   volumes:
     - './db-datavolume:/var/lib/mysql'
     - './db:/docker-entrypoint-initdb.d/'

 php:
   image: kadambkaluskar/docker-php7-ubuntu
   ports:
     - "9000:9000"
     - "80:80"
   volumes:
     - ./code:/home/kadamb/public_html
   #environment:
   #     MONGO_HOST: mongo
   #     MONGO_PORT: 27017
   links:
     - mysql
     - mongo
   tty: true
   #command : service nginx restart

volumes:
 db-datavolume:
 mongo:
#networks:
# vpcbr:
#  driver: bridge
#  ipam:
#   config:
#    - subnet: 10.5.0.0/16
